### ISSUE TITLE
好像如果探索结束有宝箱什么的不会弹出界面会导致中断。。。

### ISSUE THREAD

**Issue by zhenghuihuang** [AcademicDog/onmyoji_bot#10]
还有是否考虑判断经验满以结算界面而不是准备界面？希望可以交流毕竟这游戏太肝了= =

**Comment by AcademicDog** [comment]
可以在结算界面，我之前用的一个工具可以实现：在经验满之前自动开阵容锁定，在经验满之后关掉阵容锁定并更换狗粮，觉得这种真的很方便。

但是我现在遇到的一个问题就是：“满”字的背景也会影响满级狗粮的识别，哪怕是文件“./img/MAN1.png”和文件“./img/MAN2.png”都不能相互替换（相互代替后会因为背景不同而识别失败）。

因此，一方面我担心结算界面检测会因为背景式神影响满级识别，另一方面准备界面检测没有花费太多时间，就没有做更改。

如果想多交流的话，我建个交流Q群吧，592055060。

**Comment by AcademicDog** [comment]
因为打boss是后面更新加的，没有考虑到宝箱的情况，可以在release中找到前一个版本作为临时解决方案，我会尽快更新打完boss后的结算。
