### ISSUE TITLE
魂十乘客在离开战斗进入庭院后会点击屏幕

### ISSUE THREAD

**Issue by zhangzicao** [AcademicDog/onmyoji_bot#14]
场景：魂十
描述：结算出庭院后依旧会点击屏幕，可能进入其他界面
问题猜测：有时若司机点击的延时/疲惫值高或者网速慢时会出现这个问题

**Comment by AcademicDog** [comment]
去探索页面开车就好了，因为新版ui把图标改了

**Comment by zhangzicao** [comment]
大佬，魂十代码什么时候更新，现在用不了啊

**Comment by AcademicDog** [comment]
> 大佬，魂十代码什么时候更新，现在用不了啊

哪个用不了？魂十还是御灵？

**Comment by AcademicDog** [comment]
> 大佬，魂十代码什么时候更新，现在用不了啊

我明白了，让我想想

**Comment by zhangzicao** [comment]
探索页面组队什么意思。。。脚本里选探索能组队刷魂十？还是说现在探索支持组队刷？

**Comment by AcademicDog** [comment]
不是，就是不要在庭院里面组队，下一个更新就能修复

**Comment by AcademicDog** [comment]
最新版本应该已经修复
