### ISSUE TITLE
其他问题和建议

### ISSUE THREAD

**Issue by zhangzicao** [AcademicDog/onmyoji_bot#15]
1.可以加个刷结界突破
2.exe被腾讯管家隔离。难受，还要添加信任才能用。（另外，编译打包要退出腾讯管家才行）
3.GitHub下载已编译版速度几乎为0，能加个百度云下载地址吗
大佬能给个百度云地址吗=_=、

**Comment by AcademicDog** [comment]
1、结界突破可以添加，但是主要问题在于：自动标记还不完善，双蛇一类的阵容受限；要做到刷其他副本的同时自动清突破券很难，效果大打折扣。

2、我用avast，也隔离，我是添加整个文件夹作为白名单。

3、这个没问题链接：https://pan.baidu.com/s/1jhHrjRGWmu9yOLq9ryApJA     提取码：gyj9

**Comment by zhangzicao** [comment]
多谢大佬
结界突破如果要做，可以做先支持不用标记的双拉一波流，能凑合着用刷点体力。后面补充失败后切换阵容或者其他功能。
至于刷其他副本的同时自动清突破券我倒是没想过，实现上比较复杂。
