### ISSUE TITLE
关于脚本探索部分的一些建议

### ISSUE THREAD

**Issue by xctm** [AcademicDog/onmyoji_bot#16]
1. 建议探索关卡打完Boss后增加收取宝物的逻辑；
2. 建议探索关卡打完Boss结束后增加识别是否存在宝箱并收取的逻辑。
宝物和宝箱收益较高，而且位置比较固定，容易识别。

**Comment by AcademicDog** [comment]
目前打完Boss还有些bug需要处理，后续再添加收取宝箱。掉落宝物是自动拾取的，不用处理；掉落宝箱可以点开。

**Comment by daweinan** [comment]
大佬，目前探索是不是不包含组队功能。尝试了下好像没有效果
