### ISSUE TITLE
之后是否会考虑添加以下功能？

### ISSUE THREAD

**Issue by HelloWorld0204** [AcademicDog/onmyoji_bot#17]
先给大佬点个赞
然后想问一下之后是否会添加下面这些功能：
1.御魂超过6K之后，战斗结算时会弹出御魂过多的提示，之后是否会添加对于这个提示判断及点击：
![image](https://user-images.githubusercontent.com/32006025/65825241-55e50900-e2a7-11e9-876a-14ebd33a962c.png)

2.目前是否支持双开，甚至多开？
测试过双开下，最新活动过的句柄会比其他的在list中的位置靠前

3.是否会添加对于不同窗口大小的适配？

**Comment by AcademicDog** [comment]
1、可以增加，这个不难，只是苦于御魂满不了没法测试；
2、可以双开或多开，默认绑定最后一个激活的窗口，目前双开选项已经加上，代码还在调试；
3、现在正在尽力将与坐标相关的参数都放在文件game_pos.py中，方便调整。这个问题主要还是受限于测试设备，我只有一个台式机一个笔记本，测试了下没有摸到规律。还有些缩放125%、4K之类的不好测试。

**Comment by AcademicDog** [comment]
2、目前更新了双开功能，可以通过V5双开后直接启动。

**Comment by HelloWorld0204** [comment]
尝试自己修改添加判断及点击御魂过多的功能。
发现在fighter.py中写了段:

**Comment by AcademicDog** [comment]
这个是UI生成的，运行一遍就会产生

**Comment by AcademicDog** [comment]
后两个都已经解决了，御魂提示不想做了，懒了。
