### ISSUE TITLE
魂十组队结算点击的问题

### ISSUE THREAD

**Issue by zhangzicao** [AcademicDog/onmyoji_bot#18]
用最新版本昨天刷了4个钟组队魂十，发现还有一些问题。
（1）组队魂十好像结算点击算法还是有些问题，队长和乘客在结算成功后都可能会点击到队伍房间里的邀请按钮，不过好像基本无大碍，还能刷。
（2）昨天在刷了4个钟左右后，乘客好像出现了问题，依旧停留在黑色的结算界面。我看日志好像最后是（点击结算；检测是否进入战斗）。
（3）今天早上刷了大概1个多钟又掉了，乘客最后日志依旧是（点击结算；检测是否进入战斗），司机的日志是：（点击结算x7；点击开始战斗按钮；点击开始战斗按钮；点击开始战斗按钮；点击开始战斗按钮.......；点击开始战斗按钮失败）。我猜测可能是乘客又卡在了结算界面
（4）日志中经常有多次连续的点击结算，我猜是因为经常点到金币之后的结算道具，导致要重新点击。
（5）听说司机好像可能点着点着点到个人空间

**Comment by AcademicDog** [comment]
现在结算还是有点问题，在最新的测试版里我增加了场景的识别，提高了容错率。但是现在涉及的场景比较少，自己还回到农村老家了，暂时没法修复。

**Comment by AcademicDog** [comment]
在最新的一个版本中调整了结算方法，昨天测试一下午没有出现问题。
