### ISSUE TITLE
能否识别虚拟机内的客户端

### ISSUE THREAD

**Issue by yuqinbs** [AcademicDog/onmyoji_bot#19]
主要还是怕网易有后台检测之类的东西

**Comment by yuqinbs** [comment]
并且御魂双开部分的司机不会自动开始

**Comment by Void-1900** [comment]
不行，取不到窗口句柄，不能后台操作，可以改一改代码，不用后台操作，直接对屏幕识别、移动、点击、拖拽等操作。

**Comment by AcademicDog** [comment]
改代码可以实现，但是目前还未遇到收信的情况

**Comment by AcademicDog** [comment]
> 并且御魂双开部分的司机不会自动开始

你确认下单人司机是否正常，如果正常有可能是多线程的问题。python的多线程好像是个假多线程。
