### ISSUE TITLE
大佬，bug什么时候修复

### ISSUE THREAD

**Issue by zhangzicao** [AcademicDog/onmyoji_bot#24]
描述：暂停/关闭脚本窗口后，好像脚本还在后台运行，任旧点击屏幕然后超时后强制退出了游戏
版本：v1.0.0.1009（最新）
平台：win10

其他问题和建议：
1.御魂结算点击好像还是有问题，经常点金币和头像，听朋友说有次把好友拉黑了。难道不能点空的区域嘛？建议加快结算速度
2.建议加个御魂标记功能以便速刷魂土，毕竟没有2只sp玉藻前 >_<

**Comment by AcademicDog** [comment]
一万年过去了，终于增加了御魂标记己方式神。
