### ISSUE TITLE
自动探索有bug

### ISSUE THREAD

**Issue by sirodeneko** [AcademicDog/onmyoji_bot#28]
我是直接下载的exe,自动探索打完怪后好像无法判断是否已 点击 结算(实际已经退出结束界面) 导致脚本异常

战斗结束
点击 结算
点击 结算
...
点击 结算
点击 结算 失败!

**Comment by AcademicDog** [comment]
这个问题我也一直听说有，但是没有摸清什么原因，可以通过使用老版本（如0907）的脚本解决

**Comment by AcademicDog** [comment]
MESSAGE.png图片有问题，需要重新截取。

**Comment by sirodeneko** [comment]
截取替换即可吗

**Comment by yxHenry** [comment]
@AcademicDog 提一个小小的问题，探索的时候如果拉到场景图的最后，好像就不会判断有没有经验怪了，最后一处还有2/3个的时候没有走判定直接退出了探索

**Comment by AcademicDog** [comment]
> 截取替换即可吗

替换即可，但是在最新的版本1129中已经不再需要MESSAGE.png文件了。
