### ISSUE TITLE
大佬 我有一些代码上的问题想要请教

### ISSUE THREAD

**Issue by Vang-z** [AcademicDog/onmyoji_bot#29]
我用这个项目类似的截屏代码去对其他窗体进行截屏 但是有些窗体却是全黑的 我查阅了很多资料都没有办法解决， 尝试使用了pywinauto解决了这个问题，但是这样失去了后台截屏的能力，如果大佬方便还请大佬指点一下，谢谢大佬了

**Comment by AcademicDog** [comment]
全黑的是不是因为你最小化窗口了，还有就是窗口名对不对，能不能匹配上。

**Comment by AcademicDog** [comment]
另外注意是否有执行权限，截屏可能需要管理员方式运行。

**Comment by Vang-z** [comment]
使用了is_admin函数，确定了有管理员权限，网上有一种说法是没有找到真正的句柄所以截取下来的是黑色的图片，但是我对win32这个库不是太熟悉所以想请教一下大佬有没有碰到类似的问题

**Comment by AcademicDog** [comment]
> 使用了is_admin函数，确定了有管理员权限，网上有一种说法是没有找到真正的句柄所以截取下来的是黑色的图片，但是我对win32这个库不是太熟悉所以想请教一下大佬有没有碰到类似的问题

基本上没有吧，那你用这个脚本能正常运行吗
