### ISSUE TITLE
乘客接受组队邀请会和其他邀请混淆

### ISSUE THREAD

**Issue by sup817ch** [AcademicDog/onmyoji_bot#3]
比如和结界寄养邀请混淆（其他邀请未知）

**Comment by sup817ch** [comment]
还有 乘客如果还没上车司机就点了开始的话 脚本就卡住了

**Comment by AcademicDog** [comment]
目前的临时解决方案如iss#3分支所示。
首先增加了邀请的御魂关键字识别，使玩家只能点击御魂邀请。
然后乘客如果还没上车司机就点了开始，这个有时候不好避免，现在通过激活窗口来提醒玩家。

**Comment by AcademicDog** [comment]
此外，由于之前是灰度图片识别，司机无法区分按钮是灰色还是黄色。现在将图片识别改为彩色识别。

**Comment by AcademicDog** [comment]
同时，原先的灰度图像识别无法有效区分按钮是否激活，现在更改为彩色图像识别。
