### ISSUE TITLE
最新版本的御魂开始按钮坐标未更新，问一下这个坐标测测量方法

### ISSUE THREAD

**Issue by JyinZ** [AcademicDog/onmyoji_bot#30]
看了一下代码，刷御魂的坐标还没有更新。

**Comment by solitaire2015** [comment]
不只是改坐标那么简单，御魂选择界面变了，影响了一些判断条件。

**Comment by AcademicDog** [comment]
测量方法是截图或者使用takescreen()函数，然后用画图打开，左下角显示鼠标坐标。这次更新不是只影响单刷么？

**Comment by JyinZ** [comment]
嗯嗯，只有单刷受到了影响，主要是想试着加一下开始战斗后选中己方式神的逻辑，还想康康能不能搞一下组队探索的逻辑。所以问一下坐标测量。谢谢大佬了～
