### ISSUE TITLE
请问在mac下可以使用吗

### ISSUE THREAD

**Issue by haodedong** [AcademicDog/onmyoji_bot#33]
大佬好，请问在mac下可以使用吗

**Comment by AcademicDog** [comment]
不能，因为使用了win32api

**Comment by haodedong** [comment]
哦哦 好的




| |
东
邮箱：haodedong1996@163.com
|

签名由 网易邮箱大师 定制

在2020年01月14日 16:01，AcademicDog 写道：

不能，因为使用了win32api
