### ISSUE TITLE
使用pywin32截图失败

### ISSUE THREAD

**Issue by peachis** [AcademicDog/onmyoji_bot#34]
调试的时候发现每次调用截图子程序都输出同一张图，导致一直卡在同一个步骤，不继续执行。

请问您有遇到这种情况嘛？

换一台台式机就么有这个问题。

python==3.7 pywin32==224

**Comment by AcademicDog** [comment]
我之前没有清理内存出现过，如果你是完全运行的源码应该不会。

**Comment by peachis** [comment]
我是用的game_ctl里面的`yys.debug()`来测试的，每个循环里面
        while(1):
            self.img = self.window_full_shot()
调用一次window_full_shot()。
对于yys客户端就一直卡在第一张图，但换成任务管理器win32gui.FindWindow(None, u'任务管理器')就可以正常截实时图。

不知道您是否遇到过

**Comment by peachis** [comment]
已经找到问题的原因了，是显卡的问题，需要在集显上运行yys客户端，在独显上的数据不能直接通过pywin32读取出来，换成集显打开客户端就好了。
