### ISSUE TITLE
win7系统下无法运行

### ISSUE THREAD

**Issue by KB-learning-01** [AcademicDog/onmyoji_bot#37]
版本：1.0.1.0106
系统：windows 7
描述：我不清楚最丑的分辨率是什么意思。这是目前支持的：1600x900、1440x900、1366x76、1360x768、1280x800、1280x768、1280x720、1024x768、800x600
日志：
绑定窗口成功
1770732
激活窗口成功
Now you mood is level 1
Now you mood is level 1
目前场景：0

**Comment by AcademicDog** [comment]
1、分辨率不需要更改。
2、以前是需要更换主题，现在没有这个要求了。
3、有人反映，在非1920x1080分辨率下使用有问题，原因不明。你可以看看是不是这样的问题，也可以用调试模式看看有没有正常的截图。
4、游戏需要设置成精细画质。
