### ISSUE TITLE
探索战斗完后会卡住界面

### ISSUE THREAD

**Issue by karonhyc** [AcademicDog/onmyoji_bot#41]
探索战斗后会卡在掉落御魂和金币的界面不动，麻烦大佬看看。

**Comment by AcademicDog** [comment]
你检查下：
1、有没有锁定阵容（应该不锁定）；
2、画质是不是精细（应该是）；
3、有没有开启模型描边（应该没有）；
4、分辨率是否正常（一般能操作都是正常的）。

**Comment by AcademicDog** [comment]
目前已优化结算。
