### ISSUE TITLE
大佬 探索 可以增加一个组队的功能吗？这个不会被封号吧

### ISSUE THREAD

**Issue by NiuRc** [AcademicDog/onmyoji_bot#43]

**Comment by AcademicDog** [comment]
组队现在有人开始弄了，封号没有遇到过。

**Comment by pboymt** [comment]
@AcademicDog 我自己也写了C++版本的脚本，用了三年没封号过，好像PC端没有监测机制所以有玩法次数限制

**Comment by pboymt** [comment]
探索组队不好做，我自己的项目做到现在才只能勉强用WebSocket互联才能正常运作，简单判定是否遇到Boss不好用，因为游戏Bug有概率不会把Boss居中到视野

**Comment by AcademicDog** [comment]
> 探索组队不好做，我自己的

可以参考下 https://github.com/thanatos915/onmyoji_bot 的思路，据说稳如狗。

**Comment by AcademicDog** [comment]
已增加
