### ISSUE TITLE
双开挂着挂着突然乘客邀请不上了，是因为翻车么?

### ISSUE THREAD

**Issue by suzhaomin666** [AcademicDog/onmyoji_bot#44]
you mood level is 5
you mood level is 3
自动开始战斗失败

大佬考虑一下魂11换狗粮功能吗？

**Comment by AcademicDog** [comment]
翻车因为要重新邀请，可能会掉。下次异常退出后，可以看看log.log文件的最后几行，然后再看看img/full.png的最后截图，综合应该能分析出原因。
