### ISSUE TITLE
Windows Defender报毒

### ISSUE THREAD

**Issue by pboymt** [AcademicDog/onmyoji_bot#46]
RT，今天才开始的

**Comment by pboymt** [comment]
1.0.1.0227没事儿，前面的一律报毒Trojan:Win32/Fuery.B!cl

**Comment by AcademicDog** [comment]
不应该呀，也没有太核心的变化。我刚才用avast free扫是安全的。

**Comment by pboymt** [comment]
这个不清楚，有可能是和网易合作被盯上了？



---原始邮件---
发件人: "AcademicDog"<notifications@github.com&gt;
发送时间: 2020年2月29日(周六) 晚上10:05
收件人: "AcademicDog/onmyoji_bot"<onmyoji_bot@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Robert Lee"<pboymt@foxmail.com&gt;;
主题: Re: [AcademicDog/onmyoji_bot] Windows Defender报毒 (#46)



不应该呀，也没有太核心的变化。我刚才用avast free扫是安全的。

**Comment by AcademicDog** [comment]
不知道，反正老版本尽量别用了，几乎必遭殃。马上把新版本放出，大幅提高了结算可靠性，速度也能接受了。

**Comment by AcademicDog** [comment]
还有就是，我给你说的那个探索双开版本看了么。

**Comment by pboymt** [comment]
看了。我用不上😂



---原始邮件---
发件人: "AcademicDog"<notifications@github.com&gt;
发送时间: 2020年2月29日(周六) 晚上10:23
收件人: "AcademicDog/onmyoji_bot"<onmyoji_bot@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Robert Lee"<pboymt@foxmail.com&gt;;
主题: Re: [AcademicDog/onmyoji_bot] Windows Defender报毒 (#46)



还有就是，我给你说的那个探索双开版本看了么。

**Comment by AcademicDog** [comment]
Avast扫描安全，腾讯哈勃分析系统扫描安全，应该是误报。
