### ISSUE TITLE
电脑休眠可能导致脚本超时关闭

### ISSUE THREAD

**Issue by pboymt** [AcademicDog/onmyoji_bot#47]
RT，我自己也有做脚本但是是操作鼠标的所以不会导致电脑休眠，但是这个项目好像是直接向窗口发送事件吧？所以AFK了就会出现标题说的问题，建议既然能获取管理员权限了也想办法在脚本启动期间避免休眠的问题

**Comment by AcademicDog** [comment]
这样是可以的，但是我觉得自行修改系统设置已经超出了一个脚本应该做的事情范围。

**Comment by pboymt** [comment]
也不是很困难，几分钟一次微调鼠标位置就行



---原始邮件---
发件人: "AcademicDog"<notifications@github.com&gt;
发送时间: 2020年2月29日(周六) 晚上10:00
收件人: "AcademicDog/onmyoji_bot"<onmyoji_bot@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Robert Lee"<pboymt@foxmail.com&gt;;
主题: Re: [AcademicDog/onmyoji_bot] 电脑休眠可能导致脚本超时关闭 (#47)



这样是可以的，但是我觉得自行修改系统设置已经超出了一个脚本应该做的事情范围。

**Comment by AcademicDog** [comment]
我发起过群投票，大家的意向并不是很强烈，因此不会增加这个功能。但作为补偿，我会增加探索组队，目前代码编写完毕，正在调试稳定性。
