### ISSUE TITLE
结算界面点击问题

### ISSUE THREAD

**Issue by sup817ch** [AcademicDog/onmyoji_bot#5]
据群友反应容易点到奖励，导致脚本卡住。

**Comment by AcademicDog** [comment]
还有群友，组织很大呀

**Comment by sup817ch** [comment]
其实就是几个一起玩的寮友

**Comment by AcademicDog** [comment]
今天才出现的吗，是御魂战斗吧？

**Comment by sup817ch** [comment]
应该是御魂战斗，用的是release 0707版本

**Comment by AcademicDog** [comment]
因为结算是反复点击的，即使哪次点到了御魂上，也会随机的点到有效位置实现退出。

但是在原来的程序里面，打完之后有10s时间用于结算，而随机结算点击的周期在1-4s。在极端的情况下，4s点一次，结算时间内一共能点2下，如果其中有一次点歪了就会结算失败。

目前临时解决方案是，提高结算时间到12.5s，降低结算点击周期至0.5-2.5s，后面还会再改结算机制。

**Comment by sup817ch** [comment]
为什么不点击不会出现御魂的区域呢

**Comment by AcademicDog** [comment]
因为最大范围是3排御魂，我一直运气不好，没截到这样情况的图，就没找到边界

**Comment by sup817ch** [comment]
![QQ截图20190711154121](https://user-images.githubusercontent.com/37150533/61031731-aceae880-a3f2-11e9-8c0c-f0383e03bd0b.jpg)
尝试点击红框内的区域？我觉得这样就点不到了，我之前是这样干的。
[GetCursorClientPos.zip](https://github.com/AcademicDog/onmyoji_bot/files/3380761/GetCursorClientPos.zip)
提供一个我写脚本的时候用的取坐标的工具，打开游戏后打开此工具，隔一小段时间输出一次当前坐标，窗口pos就是相对于游戏窗口的坐标，不知道对你有没有帮助。

**Comment by AcademicDog** [comment]
我之前4开封了一次，有点害怕了，所以都尽可能的大范围截取。谢谢你的工具，我之前一直还在用画图来取坐标。

**Comment by sup817ch** [comment]
4开是真的拼，哈哈哈。
范围小一点我感觉没什么关系，我还没收到过信。

**Comment by AcademicDog** [comment]
我回滚了，调整了结算位置，之前是上下左右都会点，现在是上左右，等下我组野队试试。

现在是追求稳定，害怕检测。目前买了个比较稳定的脚本，基于模拟器，比我手点还快，每天8k体都没事。所以我觉得目前的参数还是有点裕量过剩了。

我比较担心的是win32 api的方式本身就不安全，需要更底层的窗口获取方式，也许模拟器或者虚拟机才是省事的出路。

**Comment by sup817ch** [comment]
我觉得还好吧，我用这个game_ctl已经刷了上万体力了，目前黑信还是没收到的。
只不过还没试过一天8k体力（没有那么多体力啊淦

**Comment by sup817ch** [comment]
还是尽量再缩小点击区域吧，点到什么东西的情况都有，比如聊天框、战斗数据等等，建议就点我红框的那一部分，不会有事的。

**Comment by AcademicDog** [comment]
已经缩小区域
