### ISSUE TITLE
卑弥呼副本非常容易误点怪物

### ISSUE THREAD

**Issue by pboymt** [AcademicDog/onmyoji_bot#55]
感觉点击范围的上边界应该向下调整一些，我试过几乎所有位置都大概率点不到烬天玉藻前。必须把鼠标放在想点的位置才能点到

**Comment by AcademicDog** [comment]
因为点怪只试过普通御魂副本，其他副本没有试过，可能会有些问题。由于最近有些自己的事情忙，还没来得及修复这些东西，也没来得及加新功能。
