### ISSUE TITLE
win7 64位 最新版本打不开

### ISSUE THREAD

**Issue by lja1** [AcademicDog/onmyoji_bot#57]
之前v1.0.1.0224可以打开

**Comment by Miaooo92** [comment]
requrement变了，需要安装一个新的包

**Comment by AcademicDog** [comment]
忘了从引入哪个包开始后，win7就不能运行了。

**Comment by lja1** [comment]
> 
> 
> 忘了从引入哪个包开始后，win7就不能运行了。

说错了，是之前使用的v1.0.1.0221版本能打开，v1.0.1.0224开始无法打开了。
https://github.com/AcademicDog/onmyoji_bot/compare/v1.0.1.0221...v1.0.1.0224

**Comment by DanielDcool** [comment]
win7现在有办法打开吗?

**Comment by AcademicDog** [comment]
我试了，是因为我win10编译的tkinter，在win7下不能正常运行，也许源码可以？？？
