### ISSUE TITLE
大佬加油

### ISSUE THREAD

**Issue by fhzzzs** [AcademicDog/onmyoji_bot#6]

**Comment by fhzzzs** [comment]
这个脚本挺好的，希望大佬能快快更新！

**Comment by fhzzzs** [comment]
似乎不会自动换狗粮，会直接开始战斗

**Comment by fhzzzs** [comment]
探索点经验怪似乎会点错。

**Comment by AcademicDog** [comment]
> 探索似乎不会自动换狗粮，会直接开始战斗，探索一定次数后会莫名其妙的停止运行。

晚上我试试，不知道是不是更新了之后颜色、图标有些小改动。同时你看看系统、屏幕分辨率、游戏分辨率、缩放设置是否和我用的一样。

**Comment by AcademicDog** [comment]
我试了下，没遇到你说的问题，你是不是开启了阵容锁定？

**Comment by fhzzzs** [comment]
都是一样的，没开阵容锁定，我试了几次后貌似是只会在2个狗粮都满级后才换一个。

**Comment by sup817ch** [comment]
> 都是一样的，没开阵容锁定，我试了几次后貌似是只会在2个狗粮都满级后才换一个。我似乎（喜欢）了n卡，我取消试试看

![QQ截图20190728000221](https://user-images.githubusercontent.com/37150533/61996784-ff9ef280-b0ca-11e9-8360-9d8d4c333e81.jpg)
你看看你的式神站位是不是这样
另外想百分百点经验怪有点难度。。。

**Comment by fhzzzs** [comment]
我上传个视频到youtube了，你看一下什么情况。。
https://youtu.be/nldh7cDK0-M

**Comment by fhzzzs** [comment]
> 另外想百分百点经验怪有点难度。。。

也不求百分百啦，只是想脚本尽量不要点金币怪。

**Comment by fhzzzs** [comment]
https://youtu.be/B8njFQliSt4
这个视频你看下，简介先看

**Comment by AcademicDog** [comment]
1.  你开了模型描边，不知道会不会是这个问题。

1.  这种情况，你可以试试重新截取满级判断的图片，即./img/MAN1.png和./img/MAN2.png，分别代表中间狗粮和右边狗粮。

1.  后面我会重新更新下满级狗粮的判断。

**Comment by fhzzzs** [comment]
> 2. 这种情况，你可以试试重新截取满级判断的图片，即./img/MAN1.png和./img/MAN2.png，分别代表中间狗粮和右边狗粮。

图片的大小有要求吗，如果截取整个满字可以吗？

**Comment by AcademicDog** [comment]
> 图片的大小有要求吗，如果截取整个满字可以吗？

没有，不要截到式神那里就好

**Comment by fhzzzs** [comment]
> 1. 你开了模型描边，不知道会不会是这个问题。

确实是模型描边的问题

**Comment by AcademicDog** [comment]
> 确实是模型描边的问题

不知道是上古bug还是网易调整了满字的位置，之前判断满级特征时，截取位置不太正确，目前已在最新版本1.0.0.0728中修复。

**Comment by fhzzzs** [comment]
我觉得刷怪的时候，如果刷出boss，希望可以点击boss而不是直接退出。

**Comment by fhzzzs** [comment]
经验怪有时候与其他怪站的比较近的时候，会点其他的怪而不是经验怪

**Comment by fhzzzs** [comment]
建议脚本点击结束后不直接退出。

**Comment by fhzzzs** [comment]
![0MPMURN_MU)LI(63Y6OJRQC](https://user-images.githubusercontent.com/20313988/62011440-5d642680-b12d-11e9-96c4-87b5b1c5b81a.png)
式神的高低会导致满这个字的高低。。。。。。。

**Comment by zhenghuihuang** [comment]
感觉有些地方选的判定图有问题，比如准备按钮的点击判断，不该判断点击两个字吧，两字旁边有动画效果，不如判断下面鼓的支架那个是静态的
