### ISSUE TITLE
标记式神失败

### ISSUE THREAD

**Issue by Miaooo92** [AcademicDog/onmyoji_bot#63]
使用烬琴蛇阵容刷魂十一时，需要在第二回合开始前标记烬天玉藻前。
但是脚本总是标记失败。
推测原因是 烬天玉藻前出手速度太快，御魂效果图标挡住了标记箭头，导致检测不出标记是否成功。
这个问题能够修复吗？

**Comment by AcademicDog** [comment]
如果头上看不到绿标的话，是不太好自动标记的。

另外，因为最近很多人反应出现了封号情况。目前还不知道问题出在了哪里，人心惶惶，在功能上的一些修复感觉必要性不大。我在百度网盘上传了个大漠插件的版本，不知道针对防封有没有作用。
