### ISSUE TITLE
大佬大佬

### ISSUE THREAD

**Issue by quzheng97** [AcademicDog/onmyoji_bot#7]
探索 打完怪后 不自己点一下结算吗  还要手动

**Comment by AcademicDog** [comment]
> 探索 打完怪后 不自己点一下结算吗 还要手动

应该不用手动啊，你说boss吗？

**Comment by zhenghuihuang** [comment]
我也遇到这个问题了，exe版本

**Comment by AcademicDog** [comment]
目前版本可以关掉打boss的功能，这些莫名其妙的卡住可以通过不打boss来解决
