### ISSUE TITLE
运行一段时间后游戏会闪退

### ISSUE THREAD

**Issue by ILUO** [AcademicDog/onmyoji_bot#8]
脚本运行一段时间后游戏会闪退，有时一次御魂还没刷完游戏窗口就自动关掉了。用樱饼就不会，可排除是游戏本身或者环境的原因。

**Comment by AcademicDog** [comment]
请问能附上脚本日志的最后几行上来吗

**Comment by YangCn** [comment]
我也遇到了相同的问题。以下是日志
`Wed, 21 Aug 2019 14:20:52  logsystem.py  [line:20]  INFO  Driver: Registration successful
Wed, 21 Aug 2019 14:20:52  logsystem.py  [line:20]  INFO  Driver: Activation successful
Wed, 21 Aug 2019 14:20:52  logsystem.py  [line:20]  INFO  Now you mood is level 4
Wed, 21 Aug 2019 14:20:52  logsystem.py  [line:20]  INFO  Now you mood is level 5
Wed, 21 Aug 2019 14:20:52  logsystem.py  [line:20]  INFO  Now you mood is level 1
Wed, 21 Aug 2019 14:20:55  logsystem.py  [line:20]  INFO  Driver: clicked KAI-SHI-ZHAN-DOU!
Wed, 21 Aug 2019 14:21:42  logsystem.py  [line:20]  INFO  Driver: Battle finished
Wed, 21 Aug 2019 14:21:52  logsystem.py  [line:20]  INFO  Driver: auto invited
Wed, 21 Aug 2019 14:21:53  logsystem.py  [line:20]  INFO  Driver: in team
Wed, 21 Aug 2019 14:21:57  logsystem.py  [line:20]  INFO  Driver: clicked KAI-SHI-ZHAN-DOU!
Wed, 21 Aug 2019 14:22:27  ui.py  [line:63]  INFO  Quitting!
`
看日志好像没有报错，不过在闪退之前，我点开聊天栏看了一下世界，不知道是不是这个原因。

**Comment by AcademicDog** [comment]
> 看日志好像没有报错，不过在闪退之前，我点开聊天栏看了一下世界，不知道是不是这个原因。

你这是双人御魂、司机端，在程序点击了“开始战斗”按钮后100秒未开始，然后强制退出了。

如果在在程序点击的瞬间，发生以下几种情况，会导致不能进入下一个循环而强制退出：
1、你鼠标放在了窗口内，这时候会点到其他地方；
2、窗口被最小化；

点击只有一次，没有失败后重试的机制，我可以改一改。

**Comment by AcademicDog** [comment]
最终原因确定了，参考[issue10](https://github.com/AcademicDog/onmyoji_bot/issues/10)，是因为打完boss后结算出的问题，目前临时解决方案是下载[v1.0.0.0728](https://github.com/AcademicDog/onmyoji_bot/releases/tag/1.0.0.0728_UI)或其以前的版本。
