### ISSUE TITLE
大佬.win10 1903版本用不了..阴阳师会闪退,自动也会失效.1803没有这个bug.只有新版本会有这样的情况

### ISSUE THREAD

**Issue by giddf** [AcademicDog/onmyoji_bot#9]

**Comment by AcademicDog** [comment]
我更新了numpy包和opencv-python包，重新编译了一个[版本](https://github.com/AcademicDog/onmyoji_bot/releases/tag/v1.0.0.0904_UI)，如果还是不行就没什么好办法了
